// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FitnessData struct {
	UserID    int     `json:"userId"`
	Date      int     `json:"date"`
	StepCount int     `json:"stepCount"`
	Gym       bool    `json:"gym"`
	Sport     bool    `json:"Sport"`
	SportType *string `json:"sportType,omitempty"`
	Duration  int     `json:"duration"`
}

type FitnessDataInput struct {
	UserID    int     `json:"userId"`
	Date      int     `json:"date"`
	StepCount int     `json:"stepCount"`
	Gym       bool    `json:"gym"`
	Sport     bool    `json:"Sport"`
	SportType *string `json:"sportType,omitempty"`
	Duration  int     `json:"duration"`
}

type Mutation struct {
}

type Query struct {
}
